[global]
username = tanaka012
password_cmd = pass spotify
use_keyring = true
backend = pulseaudio
device_name = spotify-audio
bitrate = 320

# If set to true, enables volume normalisation between songs.
volume_normalisation = true

# The normalisation pregain that is applied for each song.
normalisation_pregain = -10

# The displayed device type in Spotify clients.
# Can be unknown, computer, tablet, smartphone, speaker, tv,
# avr (Audio/Video Receiver), stb (Set-Top Box), and audiodongle.
device_type = computer
