# changinfg prefix to control-a 
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# changing splits
bind | split-window -h 
bind - split-window -v
unbind  '"'
unbind  %
# vim movement between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Improve colors (fix VIM issues)
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Scrollback limit
set -g history-limit 10000

# Window (buffer?) movement (similar to vim)
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Resize panes similar to VIM
bind -r L resize-pane -R 8
bind -r H resize-pane -L 8
bind -r K resize-pane -U 20
bind -r J resize-pane -D 20

# Use VIM keybindings in copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection-and-cancel


# Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# tmux dracula
set -g @plugin 'dracula/tmux'  
# Other examples:

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
