#! /bin/sh

sxhkd &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DVI-I-1 -d VI VII VIII IX X
bspc wm -O  HDMI-0 DVI-I-1
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap          40

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Color setings
bspc config focused_border_color "#d8dee8" 
bspc config normal_border_color "#2f343f"

bspc config top_padding 20

bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action3         resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &
$HOME/.config/scripts/monitor.sh &
$HOME/.config/polybar/launch.sh &
nitrogen --restore &
